# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'chat_app' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for chat_app
 pod 'Firebase/Core'
 pod 'Firebase/Auth'
 pod 'Firebase/Firestore'
  # target 'chat_app-tvOSTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

  target 'chat_appTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'chat_app-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for chat_app-tvOS

  target 'chat_app-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
